#!/usr/bin/env perl
#echo
#Reference script.  Echoes its input.
#by MagisterQuis
#Created 20130326
#Last Modified 20130407

# Copyright (c) 2013, Stuart McMurray
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the <organization> nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#Print errors (to stderr, and therefore mumble)
use strict;

use open ':encoding(utf8)';

#Important to unbuffer stdout so output gets to mumble on time.
$|=1;

#Continuously listen
while (<>) {
        #Remove trailing newline
        chomp;

        #The first of every pair of lines is the sender
        my ($uid, $chan, $name) = /\[u(\d+):c(\d+)\]\t(.*)/;

        #The second is the message
        my $msg = <>; 

        #Remove trailing newline
        chomp $msg;

        #Anything sent to stdout or stderr goes to the channel the bot's in
        #Output needs to be newline-terminated.
        printf "[u%i:c%i] %s: %s\n", $uid, $chan, $name, $msg;
}
